name: findme
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.2
  google_maps_flutter: ^2.0.10
  cloud_firestore: ^4.15.10
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  intl: ^0.18.0
  firebase_auth: ^4.18.0
  firebase_storage: ^11.6.11
  flutter_compass: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700

  